version: '3.8'

services:
  node_backend:
    container_name: node_amit
    image: node_amit:0.0.6
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - PG_DB=docker_db
      - PG_USER=amit
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=amit
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=docker_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
